### ISSUE TITLE
using dashboard 'Dark' theme makes it hard to use

### ISSUE THREAD

**Issue by juggledad** [HiroyasuNishiyama/node-red-contrib-ui-editor#1]
If you use the DARK theme in the dashboard (dashboard->Theme->Style->Dark) the 'Add' and 'Click to tune' options are almost impossible to see.

It would be nice if the two options would change color with the Dark them to make them more visible.

**Comment by HiroyasuNishiyama** [comment]
Thank you for reporting this.
As commented in the forum thread, fixed in 0.0.2.
